name: sightSync
description: "SightSync â€“ Your smart Bluetooth onboarding companion."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: 1.32.12
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  permission_handler: ^11.3.1
  supabase_flutter: ^2.8.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
